import { CONSTANTS, poolAddresses } from "./constants"

const C = CONSTANTS[import.meta.env.VITE_APP_CHAIN_ID]
const PA = poolAddresses[import.meta.env.VITE_APP_CHAIN_ID]

export const POOLS = {
    97: [
         {
            pid: 0,
            order: 0,
            address: C.FUEL_TOKEN_ADDRESS,
            single: true,
            native: true,
            name: 'FUEL',
            quoteTokenAddress: C.FUEL_TOKEN_ADDRESS,
            quoteStablePairAddress: C.FUEL_BUSD_ADDRESS,  // FUEL-BUSD stable pair address
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            logo1: 'fuel',
            logo2: ''
        },
        {
            pid: 1,
            order: 1,
            address: PA.PDOGE,
            single: true,
            native: false,
            name: 'PDOGE',
            quoteTokenAddress: PA.PDOGE, 
            quoteStablePairAddress: PA.BUSD_PDOGE,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,  
            logo1: 'polydoge',
            logo2: ''
        },
        {
            pid: 2,
            order: 2,
            address: C.BUSD_TOKEN_CONTRACT,
            single: true,
            native: false,
            name: 'BUSD',
            quoteTokenAddress: C.BUSD_TOKEN_CONTRACT,
            quoteStablePairAddress: '', 
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            logo1: 'busd',
            logo2: ''
        },
        {
            pid: 3,
            order: 3,
            address: PA.WBNB,
            single: true,
            native: false,
            name: 'WBNB',
            quoteTokenAddress: PA.WBNB, 
            quoteStablePairAddress: PA.BUSD_WBNB,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,  
            logo1: 'wbnb',
            logo2: ''
        },
        {
            pid: 4,
            order: 4,
            address: PA.BTCB,
            single: true,
            native: false,
            name: 'BTCB',
            quoteTokenAddress: PA.BTCB, 
            quoteStablePairAddress: PA.BTCB_BUSD,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,  
            logo1: 'btc',
            logo2: ''
        },
        {
            pid: 5,
            order: 5,
            address: PA.ETH,
            single: true,
            native: false,
            name: 'ETH',
            quoteTokenAddress: PA.ETH, 
            quoteStablePairAddress: PA.ETH_BUSD,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,  
            logo1: 'eth',
            logo2: ''
        },
        {
            pid: 6,
            order: 6,
            address: PA.CAKE,
            single: true,
            native: false,
            name: 'CAKE',
            quoteTokenAddress: PA.CAKE, 
            quoteStablePairAddress: PA.CAKE_BUSD,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,  
            logo1: 'cake',
            logo2: ''
        },
        {
            pid: 7,
            order: 7,
            address: C.FUEL_BUSD_ADDRESS,
            single: false,
            native: true,
            name: 'BUSD-FUEL',
            quoteTokenAddress: C.FUEL_TOKEN_ADDRESS,
            quoteStablePairAddress: C.FUEL_BUSD_ADDRESS,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: C.FUEL_TOKEN_ADDRESS + '/' + C.BUSD_TOKEN_CONTRACT,
            logo1: 'fuel',
            logo2: 'busd'
        },
        {
            pid: 8,
            order: 8,
            address: C.FUEL_WBNB,
            single: false,
            native: true,
            name: 'WBNB-FUEL',
            quoteTokenAddress: C.FUEL_TOKEN_ADDRESS,
            quoteStablePairAddress: C.FUEL_BUSD_ADDRESS,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: C.FUEL_TOKEN_ADDRESS + "/" + PA.WBNB,
            logo1: 'fuel',
            logo2: 'wbnb'
        },
        {
            pid: 9,
            order: 9,
            address: PA.BUSD_PDOGE,
            single: false,
            native: false,
            name: 'BUSD-PDOGE',
            quoteTokenAddress: C.BUSD_TOKEN_CONTRACT,
            quoteStablePairAddress: '',
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: C.BUSD_TOKEN_CONTRACT + PA.PDOGE,
            logo1: 'polydoge',
            logo2: 'busd'
        },
        {
            pid: 10,
            order: 10,
            address: PA.BUSD_WBNB,
            single: false,
            native: false,
            name: 'BUSD-WBNB',
            quoteTokenAddress: C.BUSD_TOKEN_CONTRACT,
            quoteStablePairAddress: '',
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: C.BUSD_TOKEN_CONTRACT + "/" + PA.WBNB,
            logo1: 'wbnb',
            logo2: 'busd'
        },
        {
            pid: 11,
            order: 11,
            address: PA.BUSD_USDT,
            single: false,
            native: false,
            name: 'BUSD-USDT',
            quoteTokenAddress: C.BUSD_TOKEN_CONTRACT,
            quoteStablePairAddress: "",
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: C.BUSD_TOKEN_CONTRACT + '/' + PA.USDT,
            logo1: 'usdt',
            logo2: 'busd'
        },
        {
            pid: 12,
            order: 12,
            address: PA.BUSD_USDC,
            single: false,
            native: false,
            name: 'BUSD-USDC',
            quoteTokenAddress: C.BUSD_TOKEN_CONTRACT,
            quoteStablePairAddress: "",
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: C.BUSD_TOKEN_CONTRACT + '/' + PA.USDC,
            logo1: 'usdc',
            logo2: 'busd'
        },
        {
            pid: 13,
            order: 13,
            address: PA.BTCB_ETH,
            single: false,
            native: false,
            name: 'BTCB-ETH',
            quoteTokenAddress: PA.BTCB,
            quoteStablePairAddress: PA.BTCB_BUSD,
            stableTokenAddress: C.BUSD_TOKEN_CONTRACT,
            tokenPair: PA.BTCB + "/" + PA.ETH,
            logo1: 'eth',
            logo2: 'btc'
        },
    ]
}